### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by ochan12**
Hopefully now more Spanish speakers will get on board 😃

### CODE REVIEW

**Comment by ochan12** [comment]
Will close #55

**Comment by mensch72** [comment]
For reviewers' convenience, here are some screenshots.
[spanish_vodle_screenshots.zip](https://github.com/pik-gane/vodle/files/9991729/spanish_vodle_screenshots.zip)

**Comment by mensch72** [comment]
Here's a demo poll in a test deployment: https://pik-gane.github.io/vodle/#/joinpoll/https:%2F%2Fsandstorm.pik-potsdam.de%2Fcouch%2F/none/53aa8849/674b9f7e4014d3e2
(switch languages on the "Settings" page if necessary)

**Comment by mensch72** [comment]
@ochan12 , this was super-fast! Amazing, thank you so much!

I have a question about one term: Does "encuesta" suggest that it is not only about eliciting preferences but about actually making a decision? Or would "votación" be better? Or would "votación" suggest that it is a one-off thing without any interactivity? I use "poll" in English in the sense of "going to the polls", not in the sense of "opinion poll".

**Comment by ochan12** [comment]
@mensch72  That was not an easy choice and perhaps your input here would be useful. 
- "votacion" refers to giving your vote to one or more options bot not with interactivity. Like choosing toppings for a burguer 🍔 
- "encuesta" is when you make one or more questions and you can answer with more options than just yes or no, but it's not ussually associated with making a decision so I'm not completely sure about this one, but it looked like the broadest one. 
- "eleccion" is when you have to choose only one option, like president.

So "votacion" would be right, in the sense of choosing one or more options and maybe it would look simpler. My only concern was that if votacion was used people may miss the fact they can actually give a "ranked" opinion about each of them.

**Comment by mensch72** [comment]
OK I think "encuesta" is probably OK then for now. Let's see what the reviewer says. Thank you!

**Comment by ochan12** [comment]
Encuesta sounds like a long form to fill in as voting could be more interactive, so I'm asking a couple of friends what they think as well

**Review by mensch72 — COMMENTED** [review]
Here's a first anonymous but trustworthy review: _I've been through the screenshots myself and they look very, very good translations to me. It's Spanish of Spain, not of Latin America, and after going (somewhat quickly) through all the screenshots I haven't spotted any serious mistake. All I've seen are things that, in fact, there is no unanimity about among Spanish speakers, and I seem to be in the minority. I can confidently say that you can use the translation as is and you won't be embarrassed nor make Spanish speakers angry at all._

**Comment by ochan12** [comment]
@mensch72 Funny to hear that, since I'm from Argentina 😂 . But I tried to make the translations as neutral as possible.

**Comment by mensch72** [comment]
so you successfully deceived this person from Madrid :-) that's a good sign I think.

**Review by mensch72 — APPROVED** [review]
All good

**Pull request merged**
