### PR TITLE
improve landing page

### PR DESCRIPTION
**Pull request by rakshitgondwal**
• Improved the spacing around the icons in the "it's easy" and "how to help" sections.
• Improved the centering of the icons.
• Improved the demo pull button.
• Changed the color of the footer links to white for better visibility.

### CODE REVIEW

**Review by mensch72 — CHANGES_REQUESTED** [review]
Dear Rakshit, this looks fine now on index.html! 

A final request: Could you do the same changes also to index_de.html (the German language version)? And could you also sign the Contributor License Agreement, e.g. by pressing the "Details" button next to the CLA notice on the pull request page:
image

**Comment by rakshitgondwal** [comment]
@mensch72 is this okay?

**Review by mensch72 — CHANGES_REQUESTED** [review]
on index_de.html, the centering still is a little off:
image

**Comment by rakshitgondwal** [comment]
@mensch72 done!

**Review by mensch72 — APPROVED** [review]
super, thank you Rakshit!

**Comment by rakshitgondwal** [comment]
Thanks for the merge @mensch72 !
Actually I've just started my open source journey and I was wondering if you could give me some tips to open source or mistakes that I should avoid while contributing.

**Pull request merged**
